# Deep Learning
## pytorch Basic

In [3]:
pip install torch


   ---------------------------------------- 0.0/111.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/111.0 MB 1.9 MB/s eta 0:00:58
   ---------------------------------------- 0.1/111.0 MB 787.7 kB/s eta 0:02:21
   ---------------------------------------- 0.1/111.0 MB 930.9 kB/s eta 0:02:00
   ---------------------------------------- 0.1/111.0 MB 599.1 kB/s eta 0:03:06
   ---------------------------------------- 0.1/111.0 MB 655.8 kB/s eta 0:02:50
   ---------------------------------------- 0.3/111.0 MB 1.0 MB/s eta 0:01:51
   ---------------------------------------- 0.3/111.0 MB 1.0 MB/s eta 0:01:51
   ---------------------------------------- 0.3/111.0 MB 873.8 kB/s eta 0:02:07
   ---------------------------------------- 0.4/111.0 MB 890.4 kB/s eta 0:02:05
   ---------------------------------------- 0.4/111.0 MB 890.4 kB/s eta 0:02:05
   ---------------------------------------- 0.5/111.0 MB 901.1 kB/s eta 0:02:03
   ---------------------------------------- 0.5/111.0 M


[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: C:\Users\Admin\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import torch

In [5]:
torch.cuda.is_available()

False

In [6]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df = pd.read_csv("./iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [8]:
df.shape

(150, 6)

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
x = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)

#chia dữ liệu với test size = 20%
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)   

x_train = torch.FloatTensor(x_train)
x_test = torch.FloatTensor(x_test)
y_train = torch.LongTensor(y_train).reshape(-1, 1)
y_test = torch.LongTensor(y_test).reshape(-1, 1)

In [11]:
len(y_train)

120

In [13]:
labels, counts = y_train.unique(return_counts=True)
print(labels, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [14]:
import torch

In [15]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [16]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)    


tensor(63., grad_fn=<AddBackward0>)


In [17]:
y.grad_fn

In [18]:
y.backward()

In [19]:
x.grad

tensor(93.)

In [35]:
#btvn 
# cho y = 5x^5 + 6x^3 - 3x + 1

#cho biết độ dốc của đa thức trên ở điểm nào
x = torch.tensor(1.0, requires_grad=True)
y = 5*x**5 + 6*x**3 - 3*x + 1
y.backward()
print(x.grad)
# in ra kiểu dữ liệu của tensor x
print(x.dtype)
print(x.type())

tensor(40.)
torch.float32
torch.FloatTensor


tạo 1 tensor ban đầu có giá trị là 2
định nghĩa hàm số bà tính gradient
y = x ^ 3+ 2x^2 + 5x+1
hãy tính dy/dx tại giá trị của x 
dùng phương pháp gradient descent với learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lập
# btvn 3

tạo 1 tập dữ liệu giả lập với x là số giờ học ( ngẫu nhiên từ 1 đến 10) và y là số điểm được tính theo công thức y = 3x + 5 + noise
với noise là 1 giá trị ngẫu nhiên nhỏ

1. khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
2. tính MSE
3. tính gradient
4. cập nhật tham số w và b bằng gradient descent với learning  rate alpha = 0.01
5. lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình

In [ ]:
#bai 2
import torch
x = torch.tensor([2.0], requires_grad=True)

def f(x):
    return x**3 + 2*x**2 + 5*x + 1

alpha = 0.1
iterations = 10

print("Bắt đầu Gradient Descent")
print("=" * 50)
print(f"Giá trị ban đầu: x = {x.item():.4f}")
print(f"y ban đầu = {f(x).item():.4f}")
print()

for i in range(iterations):
    y = f(x)
    
    y.backward()
    
    gradient = x.grad.item()
    
    print(f"Vòng lặp {i+1}:")
    print(f"  x = {x.item():.6f}")
    print(f"  y = {y.item():.6f}")
    print(f"  Đạo hàm dy/dx = {gradient:.6f}")  
    
    
    with torch.no_grad():  
        x -= alpha * gradient
    
    x.grad.zero_()
    
    print(f"  x_new = {x.item():.6f}")
    print("-" * 40)

print("=" * 50)
print(f"Giá trị cuối cùng: x = {x.item():.6f}")
print(f"Giá trị cuối cùng: y = {f(x).item():.6f}")


print("\nKiểm tra bằng tính toán thủ công:")
print(f"Hàm số: y = x^3 + 2x^2 + 5x + 1")
print(f"Đạo hàm: dy/dx = 3x^2 + 4x + 5")
print(f"Tại x = 2: dy/dx = 3*(2)^2 + 4*2 + 5 = 12 + 8 + 5 = 25")

In [ ]:
# Bai 3
import torch
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)
torch.manual_seed(42)

n_samples = 50
x_data = torch.rand(n_samples) * 9 + 1 

noise = torch.randn(n_samples) * 2  
y_data = 3 * x_data + 5 + noise

print("Thông tin tập dữ liệu:")
print(f"Số mẫu: {n_samples}")
print(f"x: min={x_data.min():.2f}, max={x_data.max():.2f}")
print(f"y: min={y_data.min():.2f}, max={y_data.max():.2f}")
print()

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print(f"Tham số khởi tạo:")
print(f"w = {w.item():.4f}")
print(f"b = {b.item():.4f}")
print()

alpha = 0.01
n_epochs = 100

loss_history = []
w_history = []
b_history = []

print("Bắt đầu huấn luyện...")
print("=" * 60)

for epoch in range(n_epochs):
    y_pred = w * x_data + b
    loss = torch.mean((y_pred - y_data) ** 2)
    loss.backward()
    loss_history.append(loss.item())
    w_history.append(w.item())
    b_history.append(b.item())
    
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1:3d}/{n_epochs}:")
        print(f"  Loss (MSE) = {loss.item():.4f}")
        print(f"  w = {w.item():.4f}, b = {b.item():.4f}")
        print(f"  Gradient w = {w.grad.item():.4f}, Gradient b = {b.grad.item():.4f}")
        print("-" * 40)
    
    with torch.no_grad():  
        w -= alpha * w.grad
        b -= alpha * b.grad
    
    w.grad.zero_()
    b.grad.zero_()

print("=" * 60)
print("Huấn luyện hoàn thành!")
print()
print(f"Tham số cuối cùng:")
print(f"w = {w.item():.4f} (gần với 3)")
print(f"b = {b.item():.4f} (gần với 5)")
print(f"Loss cuối cùng: {loss_history[-1]:.4f}")

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].scatter(x_data.numpy(), y_data.numpy(), alpha=0.6, label='Dữ liệu thực')
x_line = torch.linspace(1, 10, 100)
y_line = w.item() * x_line + b.item()
axes[0].plot(x_line.numpy(), y_line.numpy(), 'r-', linewidth=2, label=f'y = {w.item():.2f}x + {b.item():.2f}')
axes[0].set_xlabel('Giờ học')
axes[0].set_ylabel('Điểm số')
axes[0].set_title('Dữ liệu và đường hồi quy')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

axes[1].plot(range(1, n_epochs + 1), loss_history, 'b-', linewidth=2)
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('MSE Loss')
axes[1].set_title('Loss qua các epochs')
axes[1].grid(True, alpha=0.3)
axes[1].set_yscale('log') 

axes[2].plot(range(1, n_epochs + 1), w_history, 'r-', label='w', linewidth=2)
axes[2].plot(range(1, n_epochs + 1), b_history, 'g-', label='b', linewidth=2)
axes[2].axhline(y=3, color='r', linestyle='--', alpha=0.5, label='w thực (3)')
axes[2].axhline(y=5, color='g', linestyle='--', alpha=0.5, label='b thực (5)')
axes[2].set_xlabel('Epoch')
axes[2].set_ylabel('Giá trị tham số')
axes[2].set_title('Tham số w và b qua các epochs')
axes[2].legend()
axes[2].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

print("\nSo sánh với công thức thực tế:")
print(f"Công thức thực tế: y = 3x + 5")
print(f"Mô hình học được: y = {w.item():.4f}x + {b.item():.4f}")
print(f"Sai số w: {abs(w.item() - 3):.4f}")
print(f"Sai số b: {abs(b.item() - 5):.4f}")

print("\nDự đoán thử:")
test_hours = torch.tensor([2.0, 5.0, 8.0])
predictions = w * test_hours + b
actual = 3 * test_hours + 5

for i in range(len(test_hours)):
    print(f"Giờ học: {test_hours[i]:.1f}h")
    print(f"  Dự đoán: {predictions[i].item():.2f} điểm")
    print(f"  Thực tế (không noise): {actual[i].item():.2f} điểm")
    print()

In [20]:
import torch
import numpy as np

In [21]:
torch.__version__

'2.9.1+cpu'

In [22]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [23]:
x=torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [24]:
print(x.dtype)

torch.int64


In [29]:
print(x.type())

torch.LongTensor


In [26]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [28]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [30]:
x = torch.from_numpy(arr)
print(x)


tensor([1, 2, 3, 4, 5])


In [31]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5])


In [33]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)


tensor([0, 1, 2, 3, 4])


In [34]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


btvn 4 giải thích 2 trường hợp trên


- th1 : PyTorch copy dữ liệu từ NumPy sang một vùng nhớ mới cho Tensor x nên arr và x hoàn toàn độc lập ,Thay đổi cái này không ảnh hưởng cái kia
- th2 : chỉ thay đổi arr (NumPy array), Nhưng x đã là bản sao dữ liệu từ trước, x không liên kết bộ nhớ với arr, do đó, x không thay đổi

btvn 5 
- giúp thầy tạo tensor 
- empyty
- zeros
-ones
- random
- reshape với view và view as

In [ ]:
#1
import torch

a = torch.empty(2, 3)
print(a)


In [ ]:
#2
b = torch.zeros(2, 3)
print(b)


In [ ]:
#3
c = torch.ones(2, 3)
print(c)


In [ ]:
#4 
d = torch.rand(2, 3)
print(d)


In [ ]:
#5
#a)
x = torch.arange(6)
y = x.view(2, 3)
print(y)
#b)
z = torch.zeros(2, 3)
y2 = x.view_as(z)
print(y2)

