# deep learning
## tuần 2 : NUMPY, PANDAS, MATPLOTLIB
# NUMPY


In [1]:
# numpy là thư viện kiểu list
#vì : numpy nhanh có nhiều hàm tích hợp dễ sử dụng cho ai 
# để sử dụng numpy thì : pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list
python_list = [1,2,3]

# chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)  # kết quả: numpy.ndarray

numpy.ndarray

In [3]:
# list trong py có thể hỗ trợ nhiều loại dữ liệu trong 1 list
my_list = [1, "hello", 3.14, True]

In [4]:
my_list = [1, 2, 3, 4, 5]
numpy_list = np.array(my_list)
numpy_list

array([1, 2, 3, 4, 5])

In [5]:
# chuyển đổi kiểu dữ liệu thì sao 
numpy_list_int = numpy_list.astype(int)
numpy_list_int

array([1, 2, 3, 4, 5])

In [ ]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8]) # x = np.arange(1,9)


In [ ]:
# lấy số 4
x[3]  # kết quả: 4
# lấy 1 2 3
x[0:3]  

In [ ]:
# lấy từ 3-8 theo 3 cách
x[2:8]  # cách 1
x[2:]    # cách 2 
x[2::1]  # cách 3
# lấy 3 và 5
x[[2,4]]  # kết quả: array([3, 5])

In [7]:
# đặt danh sách các index muốn truy cập 
indices = [0,2,4,6]
x[indices]  # kết quả: array([1, 3, 5, 7])
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
#lấy số 2 
np_list[0,1]  # kết quả: 2
# lấy số 6 
np_list[2,1]  # kết quả: 6
# lấy [3,4],[5,6]
np_list[1: , :]  # kết quả: array([[3, 4], [5, 6]])
# cách 2 
np_list[[1,2], :]  # kết quả: array([[3, 4], [5, 6]])
# cách 3
np_list[-2:]
# lấy 1 3 5 
np_list[:,0]  # kết quả: array([1, 3, 5])
# cách 2 và 3 
np_list[:, [0]]  # kết quả: array([[1], [3], [5]])
np_list[:, 0:1]  # kết quả: array([[1], [3


array([[1],
       [3],
       [5]])

In [ ]:
# lấy 1 và 5 theo 2 cách
np_list[[0,2], 0]  # kết quả: array([1, 5])
np_list[[0,2], 0:1]  # kết quả: array([[
# cách 3
np_list[[0,2]][:,0]  # kết quả: array([1, 5])

array([[1],
       [5]])

In [14]:
x= [
[1,2,3,4],
[5,6,7,8],
[9,10,11,12],
[13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
# lấy 2  6 10 14
np_list[:,1]



array([ 2,  6, 10, 14])

In [17]:
# lấy 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [30]:
# lấy 4 7 10
np_list[[1,2],2]

array([ 7, 11])

In [ ]:
#lấy 16 15 14 13
np_list[3, ::-1]# cách 2
np_list[3][::-1]

array([16, 15, 14, 13])

In [ ]:
# BTVN thú vị
#• cho ma trận = [[99,99,99],
#                   [99,99,99],
#                   [99,99,99]]
#hãy tưởng tượng ô 99 trống
# giả sử 1 là x
# Giá sử 0 là o
# Lấy đầu vào từ phía X và phí 0 luân phiên
# Nếu đầu vào từ phía X là (0,0)
# ma trận sẽ trở thành
#[[x,99,99], 
# (99,99,99),
#[99,99,99]]
# Nếu đầu vào từ phía o cũng là (0,0)
#Thông báo họ nhập lại # nếu không thì điễn vào ma trận
#Thứ thách: Nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi.


In [ ]:
import numpy as np

def display_board(board):
    """Hiển thị bàn cờ"""
    for row in board:
        print(" | ".join([str(cell) if cell != 99 else " " for cell in row]))
        print("---------")

def check_winner(board, player):
    """Kiểm tra xem người chơi có thắng không"""
    for row in board:
        if all(cell == player for cell in row):
            return True
    
    for col in range(3):
        if all(board[row, col] == player for row in range(3)):
            return True

    if all(board[i, i] == player for i in range(3)):
        return True
    
    if all(board[i, 2-i] == player for i in range(3)):
        return True
    
    return False

def is_board_full(board):
    """Kiểm tra xem bàn cờ có đầy không"""
    return np.all(board != 99)

def play_tictactoe():
    """Chơi trò chơi Tic-Tac-Toe"""
    board = np.full((3, 3), 99)
    
    current_player = 1 
    player_name = {1: "X", 0: "O"}
    
    print("Chào mừng đến Tic-Tac-Toe!")
    print("X = 1, O = 0")
    print("Nhập tọa độ (hàng, cột) từ 0 đến 2\n")
    
    while True:

        display_board(board)
        

        while True:
            try:
                pos = input(f"Người chơi {player_name[current_player]} nhập tọa độ (hàng,cột): ")
                row, col = map(int, pos.split(','))
                
           
                if row < 0 or row > 2 or col < 0 or col > 2:
                    print("Tọa độ không hợp lệ! Vui lòng nhập từ 0 đến 2.")
                    continue
                
                
                if board[row, col] != 99:
                    print("Ô này đã được chiếm! Vui lòng chọn ô khác.")
                    continue
                
                # Đặt quân
                board[row, col] = current_player
                break
            except:
                print("Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)")
        
        
        if check_winner(board, current_player):
            display_board(board)
            print(f"\n🎉 Người chơi {player_name[current_player]} thắng!")
            break
        
        
        if is_board_full(board):
            display_board(board)
            print("\n🤝 Trò chơi kết thúc - Hòa!")
            break
       
        current_player = 1 - current_player


play_tictactoe()

Chào mừng đến Tic-Tac-Toe!
X = 1, O = 0
Nhập tọa độ (hàng, cột) từ 0 đến 2

  |   |  
---------
  |   |  
---------
  |   |  
---------
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
1 |   |  
---------
  |   |  
---------
  |   |  
---------
1 | 0 |  
---------
  |   |  
---------
  |   |  
---------
1 | 0 |  
---------
  |   | 1
---------
  |   |  
---------
Tọa độ không hợp lệ! Vui lòng nhập từ 0 đến 2.
1 | 0 | 0
---------
  |   | 1
---------
  |   |  
---------
Ô này đã được chiếm! Vui lòng chọn ô khác.
Ô này đã được chiếm! Vui lòng chọn ô khác.
1 | 0 | 0
---------
  | 1 | 1
---------
  |   |  
---------
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
Lỗi! Vui lòng nhập đúng định dạng: hàng,cột (ví dụ: 0,0)
Lỗi! Vui lòng nhập đúng định dạn

In [ ]:
# BTVN 2
y = np.array([
[1,2,3],
[4,5,6],
[7,8,9]
])

print("Ma trận y:")
print(y)

# 1. lấy 4,5,6 (hàng thứ 2)
print("\n1. Lấy 4,5,6:")
print(y[1, :])  # hoặc y[1]

# 2. lấy 2,5 (cột thứ 2)
print("\n2. Lấy 2,5:")
print(y[:, 1])

# 3. Lấy 3,4
print("\n3. Lấy 3,4:")
print(y[[0, 1], [2, 0]])  # hoặc 
print(np.array([y[0,2], y[1,0]]))

# 4. Lấy 9,6,3 
print("\n4. Lấy 9,6,3:")
print(y[:, 2][::-1])  # hoặc
print(y[[2, 1, 0], 2])

In [ ]:
# BTVN 3
# cho x = [1,2,3,4,5,6,7,8,9,10]
# 1. Xuất ra các giá trị lẻ sử dụng if
# 2. Xuất ra các giá trị chẵn sử dụng list comprehension

x = np.arange(1, 11)
print("Mảng x:")
print(x)

print("\n1. Các giá trị lẻ (sử dụng if):")
odd_values = x[x % 2 == 1]
print(odd_values)

print("\nCách khác (for loop với if):")
odd_list = [num for num in x if num % 2 == 1]
print(np.array(odd_list))

print("\n2. Các giá trị chẵn (sử dụng list comprehension):")
even_list = [num for num in x if num % 2 == 0]
print(np.array(even_list))

print("\nCách khác (numpy):")
print(x[x % 2 == 0])

In [33]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np_x[np_x % 2 == 0]


array([0, 2, 4, 6, 8])

In [35]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [36]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
Idx = [ True, False, True, False, True, False, True, False, True, False 
    ]
np_x[Idx]

array([0, 2, 4, 6, 8])